from .EdgeDetectionOnVgg16 import EdgeDetection as EdgeDetectionOnVgg16
from .EdgeDetectionOnMobile import EdgeDetection as EdgeDetectionOnMobile
from .PerceptualEdgeDetection import PerceptualEdgeDetection
from .PerceptualEdgeDetectionV2 import PerceptualEdgeDetection as  PerceptualEdgeDetectionV2
